/**
 * GENERATED FILE -- do not edit by hand.
 * Run `node tools/gen-graphics.mjs` to regenerate.
 *
 * Decoded from reference/galaxian_gfx.c, which comes from Jean-Francois Fabre's
 * open-source Galaxian port (https://github.com/jotd666/galaxian500). The
 * original artwork is Namco's, from the 1979 board's graphics ROMs; this is a
 * faithful recreation for a homage project, not new art.
 *
 * Pixels are 2 bits (0 = transparent, 1-3 = palette pens), packed four per byte
 * and base64 encoded. Bitmaps are already in screen orientation.
 */

/** Number of 16x16 sprites. Sprite n is built from tiles 4n..4n+3. */
export const SPRITE_COUNT = 64;
export const SPRITE_SIZE = 16;

const PACKED =
  '8D/ADzzwMDwA/DzwwD888PAPPPD8APAw/P/ADwAAAADw/wAPADzADwAPAA/APwAPAPAADzzwAA/wP/D/AAAAAMA/AD/wAMA/'
  +   'PADwPPw/PDw88Pz/PPAAPPA/ADwAAAAA/P/8PzzwPAAAPPw/AA8A8MADAPDAAzzwwAPwPwAAAADAD/AP8Dw8MDzw/DA88PAP'
  +   '/P8M/zzwDPA88PA/AAAAAPw/8D888DzwPPA88Pw/8P888ADwPPAAPPw/8A8AAAAA8P/AP/AA8PDwADwA8D88APAAPADwAPDw'
  +   '8P/APwAAAAD8//wPPAA8PDwAPPD8PzzwPAA88DwAPDw8APwPAAAAAPw/AAA88AAAPPAAAPw/AAA88AAAPPAAAPw/AAAAAAAA'
  +   'wD/AD/Dw8Dw8ADzwPAA88DwA/P/w8DzwwD888AAAAAD8//wPPAA8PDwAPPD8PzzwPAA88DwAPDw8APwPAAAAAMD/8P/wAPAA'
  +   'PADwADz88D888PAA8PDwAMD/8P8AAAAAAPA88ADwPPAA8DzwAPD8/wDwPPA88Dzw8D888AAAAAA88PD/PDwADzwPAA/8AwAP'
  +   '/A8ADzw/AA88/PD/AAAAADzw8AD88PAA/PPwAPz/8AA8//AAPPzwADzw8P8AAAAA8D888Dzw/Pw88Pz/PPD8/zzwPPM88Dzw'
  +   '8D888AAAAAD8P/w/PPA88DzwPPA8/Dzw/A/8Pzw/PAA8/DwAAAAAAPAP8D88PDzwPAA88PA/PPAA8Dz/PPA8PPA/8M8AAAAA'
  +   'PPDw/zzwAA888AAP/PwAD/A/AA/ADwAPAAMADwAAAAA88DzwPPA88DzzPPD8/zzw/P888PA8PPAwMPA/AAAAAPz/PPAA/Pz8'
  +   'AD/wP8APwA/wA/A//AD8/Pz/PPAAAAAAAADw8AAA8PAAAMAw/P/APwAAAA8AAAAPAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD//wDAAMAAwADAAMAAwADAAMAAwADA'
  +   'AMAAwP//AMAAAiIgAIKqIACouwoAgaoQAFVqFQAUKgUAAAgAAAAAAAMA//8DAAMAAwADAAMAAwADAAMAAwADAAMAAwD//wMA'
  +   'ACACACAgAgKgqqoCALgLAFCpWgFQqEoBEKACAQCAAAAAAAAAAAAAAAAAAAAAAAAAACACACAgAgKgqqoCALgLAFCpWgFQqEoB'
  +   'EKACAQCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIiAAgqogAKi7CgCBqhAAVWoVABQqBQAACAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAIAACACACAoCoIgOquCgCgKgAAlVoB'
  +   'QIVKBUABAgUAAAAAAAAAAAAAAAAAAAAAAIAIAACACACAoCoIgOquCgCgKgAAlVoBQIVKBUABAgUAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAACAIAAIgCAoioAAOgqAACgrgpQpSoIUKFaAACAUgEAAEABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAACCAAAKIoAAKAqAEClqwBQoS4IAKCqCgCAGgAAAFAAAABQAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAKCAA'
  +   'AKAqAECFiwJQpaoAAKC6AACgqgAAoIoKAAAUAgAAFAAAABQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAoAQAUCAAAVAgAAlKoA'
  +   'AKArAACoqgIAqC4AAKAqAABACAAAUCAAAFCgAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAKAEABAgBABQoAABQoAgCAqwAAoCoK'
  +   'AKiuAgCAqgAAQCAAAFAgAABUgAIAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQoAABUCAAAUAgAAkAoAAKirAACqCgAAqKsA'
  +   'AJAKAAAUAgAAFQIAAAUKAAAAAAAAAAAAAIAKAACgKgAAqKoAAKiqAAAIggBAwA4EQMAOBFDBDhXQ8T4d0P3+HdD//h/Qzc4d'
  +   '0MEMHdDBDB1QAQAVQAAABAAAAAAAAAIAAAACAAAAAgAAgAoAAKAqAAAgIgAAAAIAAMAOAEDADgRAwQ4FQPM+B0D//gdA8TwF'
  +   'QMAMBAAAAAAAAAAAqQAAAKkqAACpqgoAaVqqAmmmqSpppqmqaaapKmlaqgKpqgoAqSoAAKkAAAABAAAAAQAAAAEAAAABAAAA'
  +   'D/wAAA//AAAAPwAAAD8JAAA/qQAAP6kKD/+pqg/8qQr/A6kA/w8JAMAPAQDADwEAwA8BAMAPAQD/DwEA/wMBAAAAAAAAAAAA'
  +   'AAACAACoAgAAugsAaKprArj+rgu67+4qoP6vqujv+wq4+7oCqOnqC6iglQogQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'ABIQAACAJAAAqVIAAJQKAACoEgAAgUgAQEgRAABSQgAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAACIIAAAAEAIAQCAAQiKoC'
  +   'QKAOEACoRwVQ2i8AIJACAoAiCAhgCZEAQBBSABAQSAEAQAAAAACAAEEASAAkAAgIkAQKAgACAgCECnNAAOr/ECDwPwmZ/i8A'
  +   'APq/AoDAHwpgKAMgCAgIEAICBgKAAAIJREAAEAEEAEAAAAAAAAAAAAAAAAAAAAAAMPwPPzwMwMAw/MPAMADMwDAAzMAwDMzA'
  +   '/PADPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPADDzwMzDDDAMwwwwDDMMPAwDDDMMAww/wPDzwAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8Dw88AMMww8DAMMPwwzDDAMwwwwDMMMP8Aw88AAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AMPPAzMMMMMzDDD8MMwwwzMMMMMzDDD8AMPPAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAPA/wA888DA8APw88MA/PPDwDzzw/ADwMPz/wA8AAAAA8P8ADwA8wA8ADwAPwD8ADwDwAA888AAP8D/w/wAAAADAPwA/'
  +   '8ADAPzwA8Dz8Pzw8PPD8/zzwADzwPwA8AAAAAPz//D888DwAADz8PwAPAPDAAwDwwAM88MAD8D/w/wAA8P/wD/ADPDDwA/ww'
  +   '8APwD/ADDP/wAwzw8APwPz/AAAD/wPA//AA88PzwPPD88PD//PAA8PzwADz88PAP/w//P/8///8PPwD8Dz///w8///8PPwP8'
  +   'Dz///w8////w//D//P/w//wA8MP8APDD/ADww/wA8MP8//DD8P/wwwAAAAAAAAAAAwD/8AAAAwMAAP8AAwADAAAAAwAAAAAA'
  +   'AAAAAMADAADAAz/8AAADAwAAA/zAAwMAwAMD/wAAAAAAAAAAAAAAAAAAAAAAAAEAgEAFCIBQFQiA110LgP/9C4D+/woAOrMC'
  +   'ACijAAAgIwAAAAMAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAABAIBQBQCgVwUI4H8XCqB//wKA//8CgM6vAgDCKAAA8AgA'
  +   'ADAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAACAACAAgUAgF8FAKD/FQCAfx8IgH8/CoDz/wKAML8CAAyqAACPAgAAAwAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAoAAAACgAAgA4AAIB/FQCA/xcAgP8dAIB/HwCA8D8IAMz/CgDDvwLAoKoAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAgAIAAKgAAAA6AAAAfgUAAP5XAID+VwCAcB0AAPwfAMDDPwjw8L8CAKiqAAAACAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAoAACgCgAA4AMAAOgHAAD6VwAA8F8BAP9VAPDDXwAA8B8AAPw/AACgrgIAACoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKoA'
  +   'AKAPAADoBwAA+hcAAMBfAPD/VQEAwF8AAPoXAADoBwAAoA8AAICqAAAAAAAAAAAAAAAAAAAAAAAAAgAAgCgAAOKUAADIVQIA'
  +   'AFAIAABACAAK8AIAKoAAAKogKACqAIAAggAUAgoIEAgKCFAgCipwICoqUAiqKgAIqioAAooqoAAIKgACCCoQAgAqEAgACHAI'
  +   'AQBUAjUAhADSBSAASF8KAKCgAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAggAAgBQAACAFAABgAwAASIMAANig'
  +   'AADQqAAAKKgAAAIIAKCAgAAIgYAAWKGCABKgogAWoKqANKCqIA2giiANoIKAFKCCAFKgAgAogAAAgAJUAAAooAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAABAAAAAEAAAAAQAAQAAAABAAAAAEAAIAAQAoQAAAgFIAAAzWAAAP9gAAgAzAECgA8AUgI3IA'
  +   'wKMIAAAgIAAACCAAAA4oAKAMCADwjwIAAAAAAD8gAAAwgwMAyAwOAAKMBAApgAUAgSpUAAEAQAEAAAAFAAAAEAAAAAAAAAAA'
  +   'AAAAAAAAAAAEAABAEAAAQEANABAANACgADAACADAL8IAALrAAID86gCADAAAgAwAAAAOAAAACAAAgAIAACAAAAAIAAAACAAA'
  +   'AAgAAACAAAAAIDwAACAMAADoFwAA+AUAAGABAACgACAA1ApqAP2gcEADAHDQAwAQBAAAEAAAAAAAAAAQAAAABAEAAAEFAAAB'
  +   'pwJAAPopFAClrQcArv4/ACsqOkALSOoQCpDpBAORugNDde4AcK3uAHCvLgD/qSsA89YKAMNbAgDwKwIAwMoKAA+jKwB7vD4A'
  +   'KnU6AKplKwD7WgkAq/s2AIKqWwAAnF4AAUBPAQEAAQUBAAAUAQAAQAAAAEAEAABAUAAAAEABAAAABQCCABSA6QBQ4bsAgLpq'
  +   'AIAvmgDghaoAeIHqAeCR4gSAavgQ4Lf+4Lou/6CuPfyAW/DwgJsC/OCmCv/gazsMgK6u/wD46/oAoK76AAC97gAA6eoAQOWq'
  +   'AEChnwBAA3oAEAFAAAQAAAABAABAAAAAAQAAEAEAAAQBAAAEAUAAAQEQQAAFEFAAPQQUADU1NQDXfz0A318NAH9XD1Du1z8F'
  +   'Cv9VAMpwPQDi9w8AelUPAMpXBQDqX1UFIvUDAKJXDwAKfwUA7NcfAPxXcAD0XwMB9UANAEUANAANAVAAAQQAAQEEAAEBEAAE'
  +   'AQAAEAEAAAAAAAAABAABABAAAQBAAAQAAAEUAAAEEAAAEFAAAHBwwwBww/0AwP01AMD1NQAA1zcAAFcrAMDXiADwragAX7Wi'
  +   'VVWNqgD8L6oAcKWqAHwtqABf7+tABdzgVADX4wAANeEAQA3hAFAAzQAUQAAAAUAAQABQABAAEAAAAAAAAAAAAA==';

/**
 * All 64 sprites as one flat array of 2-bit pixel values, row-major within each
 * sprite: pixel (x, y) of sprite n is at `n * 256 + y * 16 + x`.
 * @type {Uint8Array}
 */
export const SPRITE_PIXELS = unpack(PACKED, SPRITE_COUNT * 256);

/** @param {string} b64 @param {number} length @returns {Uint8Array} */
function unpack(b64, length) {
  const binary = typeof atob === 'function'
    ? atob(b64)
    : Buffer.from(b64, 'base64').toString('binary');
  const out = new Uint8Array(length);
  for (let i = 0; i < length; i += 1) {
    out[i] = (binary.charCodeAt(i >> 2) >> ((i & 3) * 2)) & 3;
  }
  return out;
}
