/**
 * GENERATED FILE -- do not edit by hand.
 * Run `node tools/gen-graphics.mjs` to regenerate.
 *
 * Decoded from reference/galaxian_gfx.c, which comes from Jean-Francois Fabre's
 * open-source Galaxian port (https://github.com/jotd666/galaxian500). The
 * original artwork is Namco's, from the 1979 board's graphics ROMs; this is a
 * faithful recreation for a homage project, not new art.
 *
 * Pixels are 2 bits (0 = transparent, 1-3 = palette pens), packed four per byte
 * and base64 encoded. Bitmaps are already in screen orientation.
 */

/** Number of 8x8 characters in the tile set. */
export const TILE_COUNT = 256;
export const TILE_SIZE = 8;

const PACKED =
  'wA8wPDzwPPA88PAwwA8AAAAPwA8ADwAPAA8AD/D/AADwPzzwAPzAP/AP/AD8/wAA8P8APAAPwD8A8Dzw8D8AAAA/wD/wPDw8'
  +   '/P8APAA8AAD8PzwA/D8A8ADwPPDwPwAAwD/wADwA/D888Dzw8D8AAPz/PPAAPAAPwAPAA8ADAADwDzww/DDwDwz/DPDwPwAA'
  +   '8D888Dzw8P8A8AA88A8AAMAP8Dw88Dzw/P888DzwAAD8PzzwPPD8PzzwPPD8PwAAwD/w8DwAPAA8APDwwD8AAPwPPDw88Dzw'
  +   'PPA8PPwPAADw//AA8ADwP/AA8ADw/wAA/P88ADwA/D88ADwAPAAAAAAAAAAAAAAAAAAAAAAAAADAD/A8PPA88Pz/PPA88AAA'
  +   '/D888Dzw/D888Dzw/D8AAMA/8PA8ADwAPADw8MA/AAD8Dzw8PPA88DzwPDz8DwAA8P/wAPAA8D/wAPAA8P8AAPz/PAA8APw/'
  +   'PAA8ADwAAADA//AAPAA8/Dzw8PDA/wAAPPA88Dzw/P888DzwPPAAAPD/AA8ADwAPAA8AD/D/AAAA8ADwAPAA8ADwPPDwPwAA'
  +   'PPA8PDwP/AP8Dzw/PPwAAPAA8ADwAPAA8ADwAPD/AAA88Pz8/P/8/zzzPPA88AAAPPD88Pzz/P88/zz8PPAAAPA/PPA88Dzw'
  +   'PPA88PA/AAD8PzzwPPA88Pw/PAA8AAAA8D888DzwPPA8/zw88M8AAPw/PPA88Dz8/A88Pzz8AADwDzw8PADwPwDwPPDwPwAA'
  +   '8P8ADwAPAA8ADwAPAA8AADzwPPA88DzwPPA88PA/AAA88DzwPPD8/PA/wA8AAwAAPPA88Dzz/P/8//A8MDAAADzw/PzwP8AP'
  +   '8D/8/DzwAADw8PDwwDDAPwAPAA8ADwAA/P8A/AA/wA/wA/wA/P8AAAAAAAAAAPz/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AwADAAMAAwADAAMAAwCIgqiC7CqoQ'
  +   'ahUqBQgAAAAAwADAAMAAwADAAMAAwP//AAIAggCoAIEAVQAUAAAAAP//AwADAAMAAwADAAMAAwACAAICqgILAFoBSgECAQAA'
  +   'AwADAAMAAwADAAMAAwD//wAgICCgqgC4UKlQqBCgAIAAAAAAAAAAAAIAAgKqAgsAWgFKAQIBAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'ACAgIKCqALhQqVCoEKAAgAAAAAAAAAAAAAAAAAAAAAAiIKoguwqqEGoVKgUIAAAAAAAAAAAAAAAAAAAAAAAAAAACAIIAqACB'
  +   'AFUAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAgAKgiuCioAWgFKBQIFAAAAAAAAAAAAAAAAAAAAAACAAICAoIDq'
  +   'AKAAlUCFQAEAAAAAAAAAAAgACAAqCK4KKgBaAUoFAgUAAAAAAAAAAAAAAAAAAAAAAIAAgICggOoAoACVQIVAAQAAAAAAAAAA'
  +   'AAAAAAAAAgAiACoAKgCuCioIWgBSAUABAAEAAAAAAAAAAAAAAAAAAIAAgKIA6ACgUKVQoQCAAAAAAAAAAAAAAAAAAAAAAAgA'
  +   'igAqAKsALgiqChoAUABQAEAAAAAAAAAAAAAAAAAAAAIAKACgQKVQoQCgAIAAAAAAAAAAAAAAAAAAAAAAAAAgACoAiwKqALoA'
  +   'qgCKChQCFAAUAAQAAAAAAAAAAAAAIAAoAKBAhVClAKAAoACgAAAAAAAAAAAAAAAAAAAAAAoAAgACAKoAKwCqAi4AKgAIACAA'
  +   'oAAAAAAAAAAAAAAAAABABQAVAJQAoACoAKgAoABAAFAAUABQAAAAAAAAAAAKAAIACgAoAqsAKgquAqoAIAAgAIACAAAAAAAA'
  +   'AAAAAAAAQAFABQAUAIAAoACoAIAAQABQAFQAUAAAAAAAAAAAAAAKAAIAAgAKAKsACgCrAAoAAgACAAoAAAAAAAAAAAAAAAAF'
  +   'ABUAFACQAKgAqgCoAJAAFAAVAAUAAAAACgAqAKoAqgCCAA4EDgQOFT4d/h3+H84dDB0MHQAVAAQAgACgAKgAqAAIQMBAwFDB'
  +   '0PHQ/dD/0M3QwdDBUAFAAAAAAgACAAIACgAqACIAAgAOAA4EDgU+B/4HPAUMBAAAAAAAAAAAAAAAgACgACAAAADAQMBAwUDz'
  +   'QP9A8UDAAAAAAAAAAAAKAKoCqSqpqqkqqgIKAAAAAAAAAAAAAAAAAAAAqQCpKqmqaVpppmmmaaZpWqmqqSqpAAEAAQABAAEA'
  +   'AAAAAAAACQCpAKkKqaqpCqkACQABAAEAAQABAAEAAQAP/A//AD8APwA/AD8P/w/8/wP/D8APwA/AD8AP/w//AwAAAAACAAIA'
  +   'CwBrAq4L7iqvqvsKugLqC5UKAAAAAAAAAAAAAAAAAKgAumiquP6676D+6O+4+6jpqKAgQAAAAAAAAAAAAAAAABAAJABSAAoA'
  +   'EgBIABEAQgAAAAAAAAAAAAAAAAAAAAAAABIAgACpAJQAqACBQEgAUgBAAAAAAAAAAAAYAIIABAAIAKoCDhBHBS8AAgIICJEA'
  +   'UgBIAQAAgAAAAAAAAAgAAIAQEIhAoACoUNogkIAiYAlAEBAQAEAAAEgACAgKAgIAc0D/ED8JLwC/Ah8KAyAIEAYCAgkAEABA'
  +   'QQAkAJAEAAKECgDqIPCZ/gD6gMBgKAgIAgKAAERAAQQAAAAAAAAAAA8/wMDDwMzAzMDMwAM/AAAAAAAAAAAAAAAAAAAAAAAA'
  +   'MPw8DDD8MAAwADAM/PAAAAAAAAAAAAAAAAAAAAAAAAAPPDDDMMMwwzDDMMMPPAAAAAAAAAAAAAAAAAAAAAAAAPADDMwAzADD'
  +   'wMAwwPwPAAAAAAAAAAAAAAAAAAAAAAAADzwwwzDDMMMwwzDDDzwAAAAAAAAAAAAAAAAAAAAAAAD8DwDDwMDwwwDMAMz8AwAA'
  +   'AAAAAAAAAAAAAAAAAAAAAA88MMMwwzDDMMMwww88AAAAAAAAAAAAAAAAAAAAAAAA8AMMzAzM8MMMzAzM8AMAAAAAAAAAAAAA'
  +   'AADADzA8PPA88Dzw8DDADwAAAA/ADwAPAA8ADwAP8P8AAPA/PPAA/MA/8A/8APz/AADw/wA8AA/APwDwPPDwPwAAAD/AP/A8'
  +   'PDz8/wA8ADwAAPw/PAD8PwDwAPA88PA/AADAP/AAPAD8PzzwPPDwPwAA/P888AA8AA/AA8ADwAMAAPAPPDD8MPAPDP8M8PA/'
  +   'AADwPzzwPPDw/wDwADzwD/D/8P/wA/AD8APwA/AD8AM/wP/A/AD88Pzw/PD88Pzw/z///wD8/////wP8//////D/8P/ww/DD'
  +   '8MPww/DD8MP/D/8/Dz8PPw8/Dz8PPw8/8P/8//wA/AD8APwA/P/w/wAAAAD/8AMD/wADAAMAAAAAAAAAP/wDAwP8AwAD/wAA'
  +   'AAAAAAMAAAAAAAMAAAAAAAAAwAPAAwAAAADAA8ADAAAAAAAAAAABAAUIFQhdC/0L/wqzAqMAIwADAAMAAAAAAAAAAAAAAAAA'
  +   'gECAUIDXgP+A/gA6ACgAIAAAAAAAAAAAAAAAAAAAAQAFAAUIFwr/Av8CrwIoAAgAAAAAAAAAAAAAAAAAAACAAIBQoFfgf6B/'
  +   'gP+AzgDCAPAAMAAwAAAAAAAAAAAAAAAABQAFABUAHwg/Cv8CvwKqAAIAAAAAAAAAAAAAAAAIAAKAAoBfoP+Af4B/gPOAMAAM'
  +   'AI8AAwAAAAAAAAAAAAAAAAAAFQAXAB0AHwA/CP8KvwKqAAAAAAAAAAAAAAAAKAAKgA6Af4D/gP+Af4DwAMwAw8CgAAAAAAAA'
  +   'AAAAAAIAAAAAAAUAVwBXAB0AHwA/CL8CqgAIAAAAAAAAAAAAAIAAqAA6AH4A/oD+gHAA/MDD8PAAqAAAAAAAAAAAAAAoAAoA'
  +   'AwAHAFcAXwFVAF8AHwA/AK4CKgAAAAAAAAAAAAAAAKAA4ADoAPoA8AD/8MMA8AD8AKAAAAAAAAAAAAAAAACqAA8ABwAXAF8A'
  +   'VQFfABcABwAPAKoAAAAAAAAAAAAAAACAAKAA6AD6AMDw/wDAAPoA6ACgAIAAAAAAAAAAAAAAAAAAAAIACAAIAAIAAAAoAIAA'
  +   'FAIQCFAgcCAAAAAAAAKAKOKUyFUAUABACvAqgKogqgCCAAoICggKKlAIAAgAAqAAAAIQAhAIcAhUAoQAIAAKAAAAAAAAAAAA'
  +   'KiqqKqoqiioIKggqACoACAEANQDSBUhfoKAACgAAAAAAAAAAAAAAKACCgBQgBWADSIPYoNCoKKgCCICAgYChggAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAKAACABYoKKgqqCqoIqggqCCoAKAAAJUKKAAAAAAAAAAAAAAAAAAEgAWgDQgDSANgBQAUgAo'
  +   'AIAAAAAAAAAAAAAAAAAAAAAQAAQAAUAAEAAEAAEAAAAAAAAAAADAEPAFcgAIACAAAAAAAAAAAAAAAAAAAgAoQIBSDNYP9oAM'
  +   'KAAgI8CjACAgACgACAACAAAAAAADAA4ABAAFAFQAQAEABQAQAAAAAAAIAA6gDPCPAAA/IDCDyAwCjCmAgSoBAAAAAAAAAAAA'
  +   'AAAAAABAAEAAEACgAAgvwrrA/OoMAAwADgAIAAIAAAAAAAAABAAQAEANADQAMADAAAAAgACAAIAAAAAAAIAAIAAAAAAAAAAA'
  +   'PAAMABcABQABAAAgCmqgcABwABAAEAAAAAgACAAIAIAAIAAgAOgA+ABgAKAA1AD9QAPQAwQAAAAAEAAEAAEAAUAAFAAHAD8A'
  +   'OkDqEOkEugPuAO4ALgArAAAAAAABAAUApwL6KaWtrv4rKgtICpADkUN1cK1wr/+pCgACAAIACgArAD4AOgArAAkANgBbAF4A'
  +   'TwEBBQAUAEDz1sNb8CvAyg+je7wqdapl+1qr+4KqAJwBQAEAAQABAABAAEAAAAAAAIKA6eG7umovmoWqgeqR4mr4t/4u/z38'
  +   'AAAEAFAAQAEABQAUAFAAgACAAOAAeAHgBIAQ4OC6oK7w8AL8Cv87DK7/6/qu+r3u6erlqqGfA3oBQAAAAAAAAIBbgJvgpuBr'
  +   'gK4A+ACgAAAAAABAAEAAQAAQAAQAAUAAABAABAAEAAFAAFAAFAA1AD0ADQAPUD8FVQA9AA8ADwABAAEAAQABQAEQBRA9BDU1'
  +   '13/fX39X7tcK/8pw4vd6VQUAVQUDAA8ABQAfAHAAAwENADQAUAAAAQABAAQAEAAAylfqXyL1olcKf+zX/Ff0X/VARQANAQEE'
  +   'AQQBEAEAAQAAAAEAAQAEABQAEABQAHDDw/39NfU11zdXK9eIrai1ogAABAAQAEAAAAEABAAQAHAAcADAAMAAAAAAAMAA8ABf'
  +   'jaovqqWqLajv69zg1+M14Q3hAM1AAEAAUAAQAAAAAABVVQD8AHAAfABfQAVUAAAAAEAAUAAUAAFAABAAAAAAAA==';

/**
 * All 256 tiles as one flat array of 2-bit pixel values, row-major within each
 * tile: pixel (x, y) of tile n is at `n * 64 + y * 8 + x`.
 * @type {Uint8Array}
 */
export const TILE_PIXELS = unpack(PACKED, TILE_COUNT * 64);

/** @param {string} b64 @param {number} length @returns {Uint8Array} */
function unpack(b64, length) {
  const binary = typeof atob === 'function'
    ? atob(b64)
    : Buffer.from(b64, 'base64').toString('binary');
  const out = new Uint8Array(length);
  for (let i = 0; i < length; i += 1) {
    out[i] = (binary.charCodeAt(i >> 2) >> ((i & 3) * 2)) & 3;
  }
  return out;
}
